/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNewOrganizationRouteImport } from './routes/_authenticated/new-organization'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedOrganizationIdRouteRouteImport } from './routes/_authenticated/$organizationId/route'
import { Route as AuthenticatedOrganizationIdIndexRouteImport } from './routes/_authenticated/$organizationId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedAccountSettingsRouteRouteImport } from './routes/_authenticated/account/settings/route'
import { Route as AuthenticatedOrganizationIdSettingsRouteRouteImport } from './routes/_authenticated/$organizationId/settings/route'
import { Route as AuthenticatedOrganizationIdIntegrationsRouteRouteImport } from './routes/_authenticated/$organizationId/integrations/route'
import { Route as AuthenticatedOrganizationIdIntegrationsIndexRouteImport } from './routes/_authenticated/$organizationId/integrations/index'
import { Route as AuthenticatedOrganizationIdProjectsNewRouteImport } from './routes/_authenticated/$organizationId/projects/new'
import { Route as AuthenticatedAccountSettingsGeneralRouteRouteImport } from './routes/_authenticated/account/settings/general/route'
import { Route as AuthenticatedAccountSettingsAuthenticationRouteRouteImport } from './routes/_authenticated/account/settings/authentication/route'
import { Route as AuthenticatedOrganizationIdSettingsMembersRouteRouteImport } from './routes/_authenticated/$organizationId/settings/members/route'
import { Route as AuthenticatedOrganizationIdSettingsGeneralRouteRouteImport } from './routes/_authenticated/$organizationId/settings/general/route'
import { Route as AuthenticatedOrganizationIdProjectsProjectIdRouteRouteImport } from './routes/_authenticated/$organizationId/projects/$projectId/route'
import { Route as AuthenticatedAccountSettingsGeneralDeleteRouteImport } from './routes/_authenticated/account/settings/general/delete'
import { Route as AuthenticatedOrganizationIdSettingsMembersInviteRouteImport } from './routes/_authenticated/$organizationId/settings/members/invite'
import { Route as AuthenticatedOrganizationIdSettingsGeneralDeleteRouteImport } from './routes/_authenticated/$organizationId/settings/general/delete'
import { Route as AuthenticatedOrganizationIdProjectsProjectIdFeedbackRouteImport } from './routes/_authenticated/$organizationId/projects/$projectId/feedback'
import { Route as AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteImport } from './routes/_authenticated/$organizationId/projects/$projectId/settings/route'
import { Route as ApiV1OrganizationIdProjectsProjectIdFeedbackRouteImport } from './routes/api/v1/$organizationId/projects/$projectId/feedback'
import { Route as AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRouteImport } from './routes/_authenticated/$organizationId/settings/members/$memberId.delete'
import { Route as AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRouteImport } from './routes/_authenticated/$organizationId/projects/$projectId/settings/delete'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewOrganizationRoute =
  AuthenticatedNewOrganizationRouteImport.update({
    id: '/new-organization',
    path: '/new-organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationIdRouteRoute =
  AuthenticatedOrganizationIdRouteRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationIdIndexRoute =
  AuthenticatedOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccountSettingsRouteRoute =
  AuthenticatedAccountSettingsRouteRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsRouteRoute =
  AuthenticatedOrganizationIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const AuthenticatedOrganizationIdIntegrationsRouteRoute =
  AuthenticatedOrganizationIdIntegrationsRouteRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const AuthenticatedOrganizationIdIntegrationsIndexRoute =
  AuthenticatedOrganizationIdIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationIdIntegrationsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsNewRoute =
  AuthenticatedOrganizationIdProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const AuthenticatedAccountSettingsGeneralRouteRoute =
  AuthenticatedAccountSettingsGeneralRouteRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedAccountSettingsRouteRoute,
  } as any)
const AuthenticatedAccountSettingsAuthenticationRouteRoute =
  AuthenticatedAccountSettingsAuthenticationRouteRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => AuthenticatedAccountSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsMembersRouteRoute =
  AuthenticatedOrganizationIdSettingsMembersRouteRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsGeneralRouteRoute =
  AuthenticatedOrganizationIdSettingsGeneralRouteRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsProjectIdRouteRoute =
  AuthenticatedOrganizationIdProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const AuthenticatedAccountSettingsGeneralDeleteRoute =
  AuthenticatedAccountSettingsGeneralDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthenticatedAccountSettingsGeneralRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsMembersInviteRoute =
  AuthenticatedOrganizationIdSettingsMembersInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsMembersRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsGeneralDeleteRoute =
  AuthenticatedOrganizationIdSettingsGeneralDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsGeneralRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute =
  AuthenticatedOrganizationIdProjectsProjectIdFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () =>
      AuthenticatedOrganizationIdProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute =
  AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () =>
      AuthenticatedOrganizationIdProjectsProjectIdRouteRoute,
  } as any)
const ApiV1OrganizationIdProjectsProjectIdFeedbackRoute =
  ApiV1OrganizationIdProjectsProjectIdFeedbackRouteImport.update({
    id: '/api/v1/$organizationId/projects/$projectId/feedback',
    path: '/api/v1/$organizationId/projects/$projectId/feedback',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute =
  AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRouteImport.update({
    id: '/$memberId/delete',
    path: '/$memberId/delete',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsMembersRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute =
  AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () =>
      AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$organizationId': typeof AuthenticatedOrganizationIdRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/new-organization': typeof AuthenticatedNewOrganizationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/$organizationId/integrations': typeof AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren
  '/$organizationId/settings': typeof AuthenticatedOrganizationIdSettingsRouteRouteWithChildren
  '/account/settings': typeof AuthenticatedAccountSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$organizationId/': typeof AuthenticatedOrganizationIdIndexRoute
  '/$organizationId/projects/$projectId': typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/$organizationId/settings/general': typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren
  '/$organizationId/settings/members': typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren
  '/account/settings/authentication': typeof AuthenticatedAccountSettingsAuthenticationRouteRoute
  '/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRouteRouteWithChildren
  '/$organizationId/projects/new': typeof AuthenticatedOrganizationIdProjectsNewRoute
  '/$organizationId/integrations/': typeof AuthenticatedOrganizationIdIntegrationsIndexRoute
  '/$organizationId/projects/$projectId/settings': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren
  '/$organizationId/projects/$projectId/feedback': typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute
  '/$organizationId/settings/general/delete': typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRoute
  '/$organizationId/settings/members/invite': typeof AuthenticatedOrganizationIdSettingsMembersInviteRoute
  '/account/settings/general/delete': typeof AuthenticatedAccountSettingsGeneralDeleteRoute
  '/$organizationId/projects/$projectId/settings/delete': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute
  '/$organizationId/settings/members/$memberId/delete': typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/new-organization': typeof AuthenticatedNewOrganizationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/$organizationId/settings': typeof AuthenticatedOrganizationIdSettingsRouteRouteWithChildren
  '/account/settings': typeof AuthenticatedAccountSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$organizationId': typeof AuthenticatedOrganizationIdIndexRoute
  '/$organizationId/projects/$projectId': typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/$organizationId/settings/general': typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren
  '/$organizationId/settings/members': typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren
  '/account/settings/authentication': typeof AuthenticatedAccountSettingsAuthenticationRouteRoute
  '/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRouteRouteWithChildren
  '/$organizationId/projects/new': typeof AuthenticatedOrganizationIdProjectsNewRoute
  '/$organizationId/integrations': typeof AuthenticatedOrganizationIdIntegrationsIndexRoute
  '/$organizationId/projects/$projectId/settings': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren
  '/$organizationId/projects/$projectId/feedback': typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute
  '/$organizationId/settings/general/delete': typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRoute
  '/$organizationId/settings/members/invite': typeof AuthenticatedOrganizationIdSettingsMembersInviteRoute
  '/account/settings/general/delete': typeof AuthenticatedAccountSettingsGeneralDeleteRoute
  '/$organizationId/projects/$projectId/settings/delete': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute
  '/$organizationId/settings/members/$memberId/delete': typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/$organizationId': typeof AuthenticatedOrganizationIdRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/new-organization': typeof AuthenticatedNewOrganizationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$organizationId/integrations': typeof AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren
  '/_authenticated/$organizationId/settings': typeof AuthenticatedOrganizationIdSettingsRouteRouteWithChildren
  '/_authenticated/account/settings': typeof AuthenticatedAccountSettingsRouteRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/$organizationId/': typeof AuthenticatedOrganizationIdIndexRoute
  '/_authenticated/$organizationId/projects/$projectId': typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/_authenticated/$organizationId/settings/general': typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren
  '/_authenticated/$organizationId/settings/members': typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren
  '/_authenticated/account/settings/authentication': typeof AuthenticatedAccountSettingsAuthenticationRouteRoute
  '/_authenticated/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRouteRouteWithChildren
  '/_authenticated/$organizationId/projects/new': typeof AuthenticatedOrganizationIdProjectsNewRoute
  '/_authenticated/$organizationId/integrations/': typeof AuthenticatedOrganizationIdIntegrationsIndexRoute
  '/_authenticated/$organizationId/projects/$projectId/settings': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren
  '/_authenticated/$organizationId/projects/$projectId/feedback': typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute
  '/_authenticated/$organizationId/settings/general/delete': typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRoute
  '/_authenticated/$organizationId/settings/members/invite': typeof AuthenticatedOrganizationIdSettingsMembersInviteRoute
  '/_authenticated/account/settings/general/delete': typeof AuthenticatedAccountSettingsGeneralDeleteRoute
  '/_authenticated/$organizationId/projects/$projectId/settings/delete': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute
  '/_authenticated/$organizationId/settings/members/$memberId/delete': typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$organizationId'
    | '/home'
    | '/new-organization'
    | '/settings'
    | '/invite/$token'
    | '/'
    | '/$organizationId/integrations'
    | '/$organizationId/settings'
    | '/account/settings'
    | '/api/auth/$'
    | '/$organizationId/'
    | '/$organizationId/projects/$projectId'
    | '/$organizationId/settings/general'
    | '/$organizationId/settings/members'
    | '/account/settings/authentication'
    | '/account/settings/general'
    | '/$organizationId/projects/new'
    | '/$organizationId/integrations/'
    | '/$organizationId/projects/$projectId/settings'
    | '/$organizationId/projects/$projectId/feedback'
    | '/$organizationId/settings/general/delete'
    | '/$organizationId/settings/members/invite'
    | '/account/settings/general/delete'
    | '/$organizationId/projects/$projectId/settings/delete'
    | '/$organizationId/settings/members/$memberId/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/home'
    | '/new-organization'
    | '/settings'
    | '/invite/$token'
    | '/'
    | '/$organizationId/settings'
    | '/account/settings'
    | '/api/auth/$'
    | '/$organizationId'
    | '/$organizationId/projects/$projectId'
    | '/$organizationId/settings/general'
    | '/$organizationId/settings/members'
    | '/account/settings/authentication'
    | '/account/settings/general'
    | '/$organizationId/projects/new'
    | '/$organizationId/integrations'
    | '/$organizationId/projects/$projectId/settings'
    | '/$organizationId/projects/$projectId/feedback'
    | '/$organizationId/settings/general/delete'
    | '/$organizationId/settings/members/invite'
    | '/account/settings/general/delete'
    | '/$organizationId/projects/$projectId/settings/delete'
    | '/$organizationId/settings/members/$memberId/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/$organizationId'
    | '/_authenticated/home'
    | '/_authenticated/new-organization'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/_authenticated/'
    | '/_authenticated/$organizationId/integrations'
    | '/_authenticated/$organizationId/settings'
    | '/_authenticated/account/settings'
    | '/api/auth/$'
    | '/_authenticated/$organizationId/'
    | '/_authenticated/$organizationId/projects/$projectId'
    | '/_authenticated/$organizationId/settings/general'
    | '/_authenticated/$organizationId/settings/members'
    | '/_authenticated/account/settings/authentication'
    | '/_authenticated/account/settings/general'
    | '/_authenticated/$organizationId/projects/new'
    | '/_authenticated/$organizationId/integrations/'
    | '/_authenticated/$organizationId/projects/$projectId/settings'
    | '/_authenticated/$organizationId/projects/$projectId/feedback'
    | '/_authenticated/$organizationId/settings/general/delete'
    | '/_authenticated/$organizationId/settings/members/invite'
    | '/_authenticated/account/settings/general/delete'
    | '/_authenticated/$organizationId/projects/$projectId/settings/delete'
    | '/_authenticated/$organizationId/settings/members/$memberId/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiV1OrganizationIdProjectsProjectIdFeedbackRoute: typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-organization': {
      id: '/_authenticated/new-organization'
      path: '/new-organization'
      fullPath: '/new-organization'
      preLoaderRoute: typeof AuthenticatedNewOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$organizationId': {
      id: '/_authenticated/$organizationId'
      path: '/$organizationId'
      fullPath: '/$organizationId'
      preLoaderRoute: typeof AuthenticatedOrganizationIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$organizationId/': {
      id: '/_authenticated/$organizationId/'
      path: '/'
      fullPath: '/$organizationId/'
      preLoaderRoute: typeof AuthenticatedOrganizationIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/settings': {
      id: '/_authenticated/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$organizationId/settings': {
      id: '/_authenticated/$organizationId/settings'
      path: '/settings'
      fullPath: '/$organizationId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/_authenticated/$organizationId/integrations': {
      id: '/_authenticated/$organizationId/integrations'
      path: '/integrations'
      fullPath: '/$organizationId/integrations'
      preLoaderRoute: typeof AuthenticatedOrganizationIdIntegrationsRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/_authenticated/$organizationId/integrations/': {
      id: '/_authenticated/$organizationId/integrations/'
      path: '/'
      fullPath: '/$organizationId/integrations/'
      preLoaderRoute: typeof AuthenticatedOrganizationIdIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdIntegrationsRouteRoute
    }
    '/_authenticated/$organizationId/projects/new': {
      id: '/_authenticated/$organizationId/projects/new'
      path: '/projects/new'
      fullPath: '/$organizationId/projects/new'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsNewRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/_authenticated/account/settings/general': {
      id: '/_authenticated/account/settings/general'
      path: '/general'
      fullPath: '/account/settings/general'
      preLoaderRoute: typeof AuthenticatedAccountSettingsGeneralRouteRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRouteRoute
    }
    '/_authenticated/account/settings/authentication': {
      id: '/_authenticated/account/settings/authentication'
      path: '/authentication'
      fullPath: '/account/settings/authentication'
      preLoaderRoute: typeof AuthenticatedAccountSettingsAuthenticationRouteRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRouteRoute
    }
    '/_authenticated/$organizationId/settings/members': {
      id: '/_authenticated/$organizationId/settings/members'
      path: '/members'
      fullPath: '/$organizationId/settings/members'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsRouteRoute
    }
    '/_authenticated/$organizationId/settings/general': {
      id: '/_authenticated/$organizationId/settings/general'
      path: '/general'
      fullPath: '/$organizationId/settings/general'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsRouteRoute
    }
    '/_authenticated/$organizationId/projects/$projectId': {
      id: '/_authenticated/$organizationId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$organizationId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/_authenticated/account/settings/general/delete': {
      id: '/_authenticated/account/settings/general/delete'
      path: '/delete'
      fullPath: '/account/settings/general/delete'
      preLoaderRoute: typeof AuthenticatedAccountSettingsGeneralDeleteRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsGeneralRouteRoute
    }
    '/_authenticated/$organizationId/settings/members/invite': {
      id: '/_authenticated/$organizationId/settings/members/invite'
      path: '/invite'
      fullPath: '/$organizationId/settings/members/invite'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsMembersInviteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsMembersRouteRoute
    }
    '/_authenticated/$organizationId/settings/general/delete': {
      id: '/_authenticated/$organizationId/settings/general/delete'
      path: '/delete'
      fullPath: '/$organizationId/settings/general/delete'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsGeneralRouteRoute
    }
    '/_authenticated/$organizationId/projects/$projectId/feedback': {
      id: '/_authenticated/$organizationId/projects/$projectId/feedback'
      path: '/feedback'
      fullPath: '/$organizationId/projects/$projectId/feedback'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRoute
    }
    '/_authenticated/$organizationId/projects/$projectId/settings': {
      id: '/_authenticated/$organizationId/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/$organizationId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRoute
    }
    '/api/v1/$organizationId/projects/$projectId/feedback': {
      id: '/api/v1/$organizationId/projects/$projectId/feedback'
      path: '/api/v1/$organizationId/projects/$projectId/feedback'
      fullPath: '/api/v1/$organizationId/projects/$projectId/feedback'
      preLoaderRoute: typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/$organizationId/settings/members/$memberId/delete': {
      id: '/_authenticated/$organizationId/settings/members/$memberId/delete'
      path: '/$memberId/delete'
      fullPath: '/$organizationId/settings/members/$memberId/delete'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsMembersRouteRoute
    }
    '/_authenticated/$organizationId/projects/$projectId/settings/delete': {
      id: '/_authenticated/$organizationId/projects/$projectId/settings/delete'
      path: '/delete'
      fullPath: '/$organizationId/projects/$projectId/settings/delete'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute
    }
  }
}

interface AuthenticatedOrganizationIdIntegrationsRouteRouteChildren {
  AuthenticatedOrganizationIdIntegrationsIndexRoute: typeof AuthenticatedOrganizationIdIntegrationsIndexRoute
}

const AuthenticatedOrganizationIdIntegrationsRouteRouteChildren: AuthenticatedOrganizationIdIntegrationsRouteRouteChildren =
  {
    AuthenticatedOrganizationIdIntegrationsIndexRoute:
      AuthenticatedOrganizationIdIntegrationsIndexRoute,
  }

const AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren =
  AuthenticatedOrganizationIdIntegrationsRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdIntegrationsRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdSettingsGeneralRouteRouteChildren {
  AuthenticatedOrganizationIdSettingsGeneralDeleteRoute: typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRoute
}

const AuthenticatedOrganizationIdSettingsGeneralRouteRouteChildren: AuthenticatedOrganizationIdSettingsGeneralRouteRouteChildren =
  {
    AuthenticatedOrganizationIdSettingsGeneralDeleteRoute:
      AuthenticatedOrganizationIdSettingsGeneralDeleteRoute,
  }

const AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren =
  AuthenticatedOrganizationIdSettingsGeneralRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdSettingsGeneralRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdSettingsMembersRouteRouteChildren {
  AuthenticatedOrganizationIdSettingsMembersInviteRoute: typeof AuthenticatedOrganizationIdSettingsMembersInviteRoute
  AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute: typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute
}

const AuthenticatedOrganizationIdSettingsMembersRouteRouteChildren: AuthenticatedOrganizationIdSettingsMembersRouteRouteChildren =
  {
    AuthenticatedOrganizationIdSettingsMembersInviteRoute:
      AuthenticatedOrganizationIdSettingsMembersInviteRoute,
    AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute:
      AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute,
  }

const AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren =
  AuthenticatedOrganizationIdSettingsMembersRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdSettingsMembersRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdSettingsRouteRouteChildren {
  AuthenticatedOrganizationIdSettingsGeneralRouteRoute: typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren
  AuthenticatedOrganizationIdSettingsMembersRouteRoute: typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren
}

const AuthenticatedOrganizationIdSettingsRouteRouteChildren: AuthenticatedOrganizationIdSettingsRouteRouteChildren =
  {
    AuthenticatedOrganizationIdSettingsGeneralRouteRoute:
      AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren,
    AuthenticatedOrganizationIdSettingsMembersRouteRoute:
      AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren,
  }

const AuthenticatedOrganizationIdSettingsRouteRouteWithChildren =
  AuthenticatedOrganizationIdSettingsRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdSettingsRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteChildren {
  AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute
}

const AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteChildren: AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteChildren =
  {
    AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute:
      AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute,
  }

const AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren =
  AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdProjectsProjectIdRouteRouteChildren {
  AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren
  AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute
}

const AuthenticatedOrganizationIdProjectsProjectIdRouteRouteChildren: AuthenticatedOrganizationIdProjectsProjectIdRouteRouteChildren =
  {
    AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute:
      AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren,
    AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute:
      AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute,
  }

const AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren =
  AuthenticatedOrganizationIdProjectsProjectIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdProjectsProjectIdRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdRouteRouteChildren {
  AuthenticatedOrganizationIdIntegrationsRouteRoute: typeof AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren
  AuthenticatedOrganizationIdSettingsRouteRoute: typeof AuthenticatedOrganizationIdSettingsRouteRouteWithChildren
  AuthenticatedOrganizationIdIndexRoute: typeof AuthenticatedOrganizationIdIndexRoute
  AuthenticatedOrganizationIdProjectsProjectIdRouteRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren
  AuthenticatedOrganizationIdProjectsNewRoute: typeof AuthenticatedOrganizationIdProjectsNewRoute
}

const AuthenticatedOrganizationIdRouteRouteChildren: AuthenticatedOrganizationIdRouteRouteChildren =
  {
    AuthenticatedOrganizationIdIntegrationsRouteRoute:
      AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren,
    AuthenticatedOrganizationIdSettingsRouteRoute:
      AuthenticatedOrganizationIdSettingsRouteRouteWithChildren,
    AuthenticatedOrganizationIdIndexRoute:
      AuthenticatedOrganizationIdIndexRoute,
    AuthenticatedOrganizationIdProjectsProjectIdRouteRoute:
      AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren,
    AuthenticatedOrganizationIdProjectsNewRoute:
      AuthenticatedOrganizationIdProjectsNewRoute,
  }

const AuthenticatedOrganizationIdRouteRouteWithChildren =
  AuthenticatedOrganizationIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdRouteRouteChildren,
  )

interface AuthenticatedAccountSettingsGeneralRouteRouteChildren {
  AuthenticatedAccountSettingsGeneralDeleteRoute: typeof AuthenticatedAccountSettingsGeneralDeleteRoute
}

const AuthenticatedAccountSettingsGeneralRouteRouteChildren: AuthenticatedAccountSettingsGeneralRouteRouteChildren =
  {
    AuthenticatedAccountSettingsGeneralDeleteRoute:
      AuthenticatedAccountSettingsGeneralDeleteRoute,
  }

const AuthenticatedAccountSettingsGeneralRouteRouteWithChildren =
  AuthenticatedAccountSettingsGeneralRouteRoute._addFileChildren(
    AuthenticatedAccountSettingsGeneralRouteRouteChildren,
  )

interface AuthenticatedAccountSettingsRouteRouteChildren {
  AuthenticatedAccountSettingsAuthenticationRouteRoute: typeof AuthenticatedAccountSettingsAuthenticationRouteRoute
  AuthenticatedAccountSettingsGeneralRouteRoute: typeof AuthenticatedAccountSettingsGeneralRouteRouteWithChildren
}

const AuthenticatedAccountSettingsRouteRouteChildren: AuthenticatedAccountSettingsRouteRouteChildren =
  {
    AuthenticatedAccountSettingsAuthenticationRouteRoute:
      AuthenticatedAccountSettingsAuthenticationRouteRoute,
    AuthenticatedAccountSettingsGeneralRouteRoute:
      AuthenticatedAccountSettingsGeneralRouteRouteWithChildren,
  }

const AuthenticatedAccountSettingsRouteRouteWithChildren =
  AuthenticatedAccountSettingsRouteRoute._addFileChildren(
    AuthenticatedAccountSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrganizationIdRouteRoute: typeof AuthenticatedOrganizationIdRouteRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNewOrganizationRoute: typeof AuthenticatedNewOrganizationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountSettingsRouteRoute: typeof AuthenticatedAccountSettingsRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrganizationIdRouteRoute:
    AuthenticatedOrganizationIdRouteRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNewOrganizationRoute: AuthenticatedNewOrganizationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountSettingsRouteRoute:
    AuthenticatedAccountSettingsRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiV1OrganizationIdProjectsProjectIdFeedbackRoute:
    ApiV1OrganizationIdProjectsProjectIdFeedbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
