/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedNewOrganizationRouteImport } from './routes/_authenticated/new-organization'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedDocsRouteRouteImport } from './routes/_authenticated/docs/route'
import { Route as AuthenticatedOrganizationIdRouteRouteImport } from './routes/_authenticated/$organizationId/route'
import { Route as AuthenticatedDocsIndexRouteImport } from './routes/_authenticated/docs/index'
import { Route as AuthenticatedOrganizationIdIndexRouteImport } from './routes/_authenticated/$organizationId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AuthenticatedDocsRateLimitingRouteImport } from './routes/_authenticated/docs/rate-limiting'
import { Route as AuthenticatedDocsProjectsRouteImport } from './routes/_authenticated/docs/projects'
import { Route as AuthenticatedDocsOrganizationsRouteImport } from './routes/_authenticated/docs/organizations'
import { Route as AuthenticatedDocsNotificationsRouteImport } from './routes/_authenticated/docs/notifications'
import { Route as AuthenticatedDocsFeedbackRouteImport } from './routes/_authenticated/docs/feedback'
import { Route as AuthenticatedDocsAuthRouteImport } from './routes/_authenticated/docs/auth'
import { Route as ApiV1OrganizationIdRouteRouteImport } from './routes/api/v1/$organizationId/route'
import { Route as AuthenticatedAccountSettingsRouteRouteImport } from './routes/_authenticated/account/settings/route'
import { Route as AuthenticatedOrganizationIdSettingsRouteRouteImport } from './routes/_authenticated/$organizationId/settings/route'
import { Route as AuthenticatedOrganizationIdIntegrationsRouteRouteImport } from './routes/_authenticated/$organizationId/integrations/route'
import { Route as AuthenticatedOrganizationIdIntegrationsIndexRouteImport } from './routes/_authenticated/$organizationId/integrations/index'
import { Route as AuthenticatedDocsApiProjectsRouteImport } from './routes/_authenticated/docs/api/projects'
import { Route as AuthenticatedDocsApiOverviewRouteImport } from './routes/_authenticated/docs/api/overview'
import { Route as AuthenticatedDocsApiOrganizationsRouteImport } from './routes/_authenticated/docs/api/organizations'
import { Route as AuthenticatedDocsApiFeedbackRouteImport } from './routes/_authenticated/docs/api/feedback'
import { Route as AuthenticatedDocsApiAuthRouteImport } from './routes/_authenticated/docs/api/auth'
import { Route as AuthenticatedOrganizationIdProjectsNewRouteImport } from './routes/_authenticated/$organizationId/projects/new'
import { Route as ApiV1OrganizationIdProjectsRouteRouteImport } from './routes/api/v1/$organizationId/projects/route'
import { Route as AuthenticatedAccountSettingsGeneralRouteRouteImport } from './routes/_authenticated/account/settings/general/route'
import { Route as AuthenticatedAccountSettingsAuthenticationRouteRouteImport } from './routes/_authenticated/account/settings/authentication/route'
import { Route as AuthenticatedOrganizationIdSettingsMembersRouteRouteImport } from './routes/_authenticated/$organizationId/settings/members/route'
import { Route as AuthenticatedOrganizationIdSettingsGeneralRouteRouteImport } from './routes/_authenticated/$organizationId/settings/general/route'
import { Route as AuthenticatedOrganizationIdSettingsApiKeysRouteRouteImport } from './routes/_authenticated/$organizationId/settings/api-keys/route'
import { Route as AuthenticatedOrganizationIdProjectsProjectIdRouteRouteImport } from './routes/_authenticated/$organizationId/projects/$projectId/route'
import { Route as AuthenticatedAccountSettingsGeneralDeleteRouteImport } from './routes/_authenticated/account/settings/general/delete'
import { Route as AuthenticatedOrganizationIdSettingsMembersInviteRouteImport } from './routes/_authenticated/$organizationId/settings/members/invite'
import { Route as AuthenticatedOrganizationIdSettingsGeneralDeleteRouteImport } from './routes/_authenticated/$organizationId/settings/general/delete'
import { Route as AuthenticatedOrganizationIdSettingsApiKeysNewRouteImport } from './routes/_authenticated/$organizationId/settings/api-keys/new'
import { Route as AuthenticatedOrganizationIdProjectsProjectIdFeedbackRouteImport } from './routes/_authenticated/$organizationId/projects/$projectId/feedback'
import { Route as ApiV1OrganizationIdProjectsProjectIdRouteRouteImport } from './routes/api/v1/$organizationId/projects/$projectId/route'
import { Route as AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteImport } from './routes/_authenticated/$organizationId/projects/$projectId/settings/route'
import { Route as AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRouteImport } from './routes/_authenticated/$organizationId/settings/members/$memberId.delete'
import { Route as AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRouteImport } from './routes/_authenticated/$organizationId/settings/api-keys/$apiKeyId.delete'
import { Route as AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRouteImport } from './routes/_authenticated/$organizationId/projects/$projectId/settings/delete'
import { Route as ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteImport } from './routes/api/v1/$organizationId/projects/$projectId/feedback/route'
import { Route as ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRouteImport } from './routes/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewOrganizationRoute =
  AuthenticatedNewOrganizationRouteImport.update({
    id: '/new-organization',
    path: '/new-organization',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocsRouteRoute = AuthenticatedDocsRouteRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrganizationIdRouteRoute =
  AuthenticatedOrganizationIdRouteRouteImport.update({
    id: '/$organizationId',
    path: '/$organizationId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocsIndexRoute = AuthenticatedDocsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedDocsRouteRoute,
} as any)
const AuthenticatedOrganizationIdIndexRoute =
  AuthenticatedOrganizationIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDocsRateLimitingRoute =
  AuthenticatedDocsRateLimitingRouteImport.update({
    id: '/rate-limiting',
    path: '/rate-limiting',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsProjectsRoute =
  AuthenticatedDocsProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsOrganizationsRoute =
  AuthenticatedDocsOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsNotificationsRoute =
  AuthenticatedDocsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsFeedbackRoute =
  AuthenticatedDocsFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsAuthRoute = AuthenticatedDocsAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => AuthenticatedDocsRouteRoute,
} as any)
const ApiV1OrganizationIdRouteRoute =
  ApiV1OrganizationIdRouteRouteImport.update({
    id: '/api/v1/$organizationId',
    path: '/api/v1/$organizationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccountSettingsRouteRoute =
  AuthenticatedAccountSettingsRouteRouteImport.update({
    id: '/account/settings',
    path: '/account/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsRouteRoute =
  AuthenticatedOrganizationIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const AuthenticatedOrganizationIdIntegrationsRouteRoute =
  AuthenticatedOrganizationIdIntegrationsRouteRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const AuthenticatedOrganizationIdIntegrationsIndexRoute =
  AuthenticatedOrganizationIdIntegrationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedOrganizationIdIntegrationsRouteRoute,
  } as any)
const AuthenticatedDocsApiProjectsRoute =
  AuthenticatedDocsApiProjectsRouteImport.update({
    id: '/api/projects',
    path: '/api/projects',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsApiOverviewRoute =
  AuthenticatedDocsApiOverviewRouteImport.update({
    id: '/api/overview',
    path: '/api/overview',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsApiOrganizationsRoute =
  AuthenticatedDocsApiOrganizationsRouteImport.update({
    id: '/api/organizations',
    path: '/api/organizations',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsApiFeedbackRoute =
  AuthenticatedDocsApiFeedbackRouteImport.update({
    id: '/api/feedback',
    path: '/api/feedback',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedDocsApiAuthRoute =
  AuthenticatedDocsApiAuthRouteImport.update({
    id: '/api/auth',
    path: '/api/auth',
    getParentRoute: () => AuthenticatedDocsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsNewRoute =
  AuthenticatedOrganizationIdProjectsNewRouteImport.update({
    id: '/projects/new',
    path: '/projects/new',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const ApiV1OrganizationIdProjectsRouteRoute =
  ApiV1OrganizationIdProjectsRouteRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => ApiV1OrganizationIdRouteRoute,
  } as any)
const AuthenticatedAccountSettingsGeneralRouteRoute =
  AuthenticatedAccountSettingsGeneralRouteRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedAccountSettingsRouteRoute,
  } as any)
const AuthenticatedAccountSettingsAuthenticationRouteRoute =
  AuthenticatedAccountSettingsAuthenticationRouteRouteImport.update({
    id: '/authentication',
    path: '/authentication',
    getParentRoute: () => AuthenticatedAccountSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsMembersRouteRoute =
  AuthenticatedOrganizationIdSettingsMembersRouteRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsGeneralRouteRoute =
  AuthenticatedOrganizationIdSettingsGeneralRouteRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsApiKeysRouteRoute =
  AuthenticatedOrganizationIdSettingsApiKeysRouteRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsProjectIdRouteRoute =
  AuthenticatedOrganizationIdProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedOrganizationIdRouteRoute,
  } as any)
const AuthenticatedAccountSettingsGeneralDeleteRoute =
  AuthenticatedAccountSettingsGeneralDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthenticatedAccountSettingsGeneralRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsMembersInviteRoute =
  AuthenticatedOrganizationIdSettingsMembersInviteRouteImport.update({
    id: '/invite',
    path: '/invite',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsMembersRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsGeneralDeleteRoute =
  AuthenticatedOrganizationIdSettingsGeneralDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsGeneralRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsApiKeysNewRoute =
  AuthenticatedOrganizationIdSettingsApiKeysNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsApiKeysRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute =
  AuthenticatedOrganizationIdProjectsProjectIdFeedbackRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () =>
      AuthenticatedOrganizationIdProjectsProjectIdRouteRoute,
  } as any)
const ApiV1OrganizationIdProjectsProjectIdRouteRoute =
  ApiV1OrganizationIdProjectsProjectIdRouteRouteImport.update({
    id: '/$projectId',
    path: '/$projectId',
    getParentRoute: () => ApiV1OrganizationIdProjectsRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute =
  AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () =>
      AuthenticatedOrganizationIdProjectsProjectIdRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute =
  AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRouteImport.update({
    id: '/$memberId/delete',
    path: '/$memberId/delete',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsMembersRouteRoute,
  } as any)
const AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRoute =
  AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRouteImport.update({
    id: '/$apiKeyId/delete',
    path: '/$apiKeyId/delete',
    getParentRoute: () => AuthenticatedOrganizationIdSettingsApiKeysRouteRoute,
  } as any)
const AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute =
  AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRouteImport.update({
    id: '/delete',
    path: '/delete',
    getParentRoute: () =>
      AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute,
  } as any)
const ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRoute =
  ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteImport.update({
    id: '/feedback',
    path: '/feedback',
    getParentRoute: () => ApiV1OrganizationIdProjectsProjectIdRouteRoute,
  } as any)
const ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRoute =
  ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRouteImport.update({
    id: '/$feedbackId',
    path: '/$feedbackId',
    getParentRoute: () =>
      ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$organizationId': typeof AuthenticatedOrganizationIdRouteRouteWithChildren
  '/docs': typeof AuthenticatedDocsRouteRouteWithChildren
  '/home': typeof AuthenticatedHomeRoute
  '/new-organization': typeof AuthenticatedNewOrganizationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/$organizationId/integrations': typeof AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren
  '/$organizationId/settings': typeof AuthenticatedOrganizationIdSettingsRouteRouteWithChildren
  '/account/settings': typeof AuthenticatedAccountSettingsRouteRouteWithChildren
  '/api/v1/$organizationId': typeof ApiV1OrganizationIdRouteRouteWithChildren
  '/docs/auth': typeof AuthenticatedDocsAuthRoute
  '/docs/feedback': typeof AuthenticatedDocsFeedbackRoute
  '/docs/notifications': typeof AuthenticatedDocsNotificationsRoute
  '/docs/organizations': typeof AuthenticatedDocsOrganizationsRoute
  '/docs/projects': typeof AuthenticatedDocsProjectsRoute
  '/docs/rate-limiting': typeof AuthenticatedDocsRateLimitingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$organizationId/': typeof AuthenticatedOrganizationIdIndexRoute
  '/docs/': typeof AuthenticatedDocsIndexRoute
  '/$organizationId/projects/$projectId': typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/$organizationId/settings/api-keys': typeof AuthenticatedOrganizationIdSettingsApiKeysRouteRouteWithChildren
  '/$organizationId/settings/general': typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren
  '/$organizationId/settings/members': typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren
  '/account/settings/authentication': typeof AuthenticatedAccountSettingsAuthenticationRouteRoute
  '/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRouteRouteWithChildren
  '/api/v1/$organizationId/projects': typeof ApiV1OrganizationIdProjectsRouteRouteWithChildren
  '/$organizationId/projects/new': typeof AuthenticatedOrganizationIdProjectsNewRoute
  '/docs/api/auth': typeof AuthenticatedDocsApiAuthRoute
  '/docs/api/feedback': typeof AuthenticatedDocsApiFeedbackRoute
  '/docs/api/organizations': typeof AuthenticatedDocsApiOrganizationsRoute
  '/docs/api/overview': typeof AuthenticatedDocsApiOverviewRoute
  '/docs/api/projects': typeof AuthenticatedDocsApiProjectsRoute
  '/$organizationId/integrations/': typeof AuthenticatedOrganizationIdIntegrationsIndexRoute
  '/$organizationId/projects/$projectId/settings': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren
  '/api/v1/$organizationId/projects/$projectId': typeof ApiV1OrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/$organizationId/projects/$projectId/feedback': typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute
  '/$organizationId/settings/api-keys/new': typeof AuthenticatedOrganizationIdSettingsApiKeysNewRoute
  '/$organizationId/settings/general/delete': typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRoute
  '/$organizationId/settings/members/invite': typeof AuthenticatedOrganizationIdSettingsMembersInviteRoute
  '/account/settings/general/delete': typeof AuthenticatedAccountSettingsGeneralDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteWithChildren
  '/$organizationId/projects/$projectId/settings/delete': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute
  '/$organizationId/settings/api-keys/$apiKeyId/delete': typeof AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRoute
  '/$organizationId/settings/members/$memberId/delete': typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/home': typeof AuthenticatedHomeRoute
  '/new-organization': typeof AuthenticatedNewOrganizationRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/': typeof AuthenticatedIndexRoute
  '/$organizationId/settings': typeof AuthenticatedOrganizationIdSettingsRouteRouteWithChildren
  '/account/settings': typeof AuthenticatedAccountSettingsRouteRouteWithChildren
  '/api/v1/$organizationId': typeof ApiV1OrganizationIdRouteRouteWithChildren
  '/docs/auth': typeof AuthenticatedDocsAuthRoute
  '/docs/feedback': typeof AuthenticatedDocsFeedbackRoute
  '/docs/notifications': typeof AuthenticatedDocsNotificationsRoute
  '/docs/organizations': typeof AuthenticatedDocsOrganizationsRoute
  '/docs/projects': typeof AuthenticatedDocsProjectsRoute
  '/docs/rate-limiting': typeof AuthenticatedDocsRateLimitingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/$organizationId': typeof AuthenticatedOrganizationIdIndexRoute
  '/docs': typeof AuthenticatedDocsIndexRoute
  '/$organizationId/projects/$projectId': typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/$organizationId/settings/api-keys': typeof AuthenticatedOrganizationIdSettingsApiKeysRouteRouteWithChildren
  '/$organizationId/settings/general': typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren
  '/$organizationId/settings/members': typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren
  '/account/settings/authentication': typeof AuthenticatedAccountSettingsAuthenticationRouteRoute
  '/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRouteRouteWithChildren
  '/api/v1/$organizationId/projects': typeof ApiV1OrganizationIdProjectsRouteRouteWithChildren
  '/$organizationId/projects/new': typeof AuthenticatedOrganizationIdProjectsNewRoute
  '/docs/api/auth': typeof AuthenticatedDocsApiAuthRoute
  '/docs/api/feedback': typeof AuthenticatedDocsApiFeedbackRoute
  '/docs/api/organizations': typeof AuthenticatedDocsApiOrganizationsRoute
  '/docs/api/overview': typeof AuthenticatedDocsApiOverviewRoute
  '/docs/api/projects': typeof AuthenticatedDocsApiProjectsRoute
  '/$organizationId/integrations': typeof AuthenticatedOrganizationIdIntegrationsIndexRoute
  '/$organizationId/projects/$projectId/settings': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren
  '/api/v1/$organizationId/projects/$projectId': typeof ApiV1OrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/$organizationId/projects/$projectId/feedback': typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute
  '/$organizationId/settings/api-keys/new': typeof AuthenticatedOrganizationIdSettingsApiKeysNewRoute
  '/$organizationId/settings/general/delete': typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRoute
  '/$organizationId/settings/members/invite': typeof AuthenticatedOrganizationIdSettingsMembersInviteRoute
  '/account/settings/general/delete': typeof AuthenticatedAccountSettingsGeneralDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteWithChildren
  '/$organizationId/projects/$projectId/settings/delete': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute
  '/$organizationId/settings/api-keys/$apiKeyId/delete': typeof AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRoute
  '/$organizationId/settings/members/$memberId/delete': typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/$organizationId': typeof AuthenticatedOrganizationIdRouteRouteWithChildren
  '/_authenticated/docs': typeof AuthenticatedDocsRouteRouteWithChildren
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/new-organization': typeof AuthenticatedNewOrganizationRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/$organizationId/integrations': typeof AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren
  '/_authenticated/$organizationId/settings': typeof AuthenticatedOrganizationIdSettingsRouteRouteWithChildren
  '/_authenticated/account/settings': typeof AuthenticatedAccountSettingsRouteRouteWithChildren
  '/api/v1/$organizationId': typeof ApiV1OrganizationIdRouteRouteWithChildren
  '/_authenticated/docs/auth': typeof AuthenticatedDocsAuthRoute
  '/_authenticated/docs/feedback': typeof AuthenticatedDocsFeedbackRoute
  '/_authenticated/docs/notifications': typeof AuthenticatedDocsNotificationsRoute
  '/_authenticated/docs/organizations': typeof AuthenticatedDocsOrganizationsRoute
  '/_authenticated/docs/projects': typeof AuthenticatedDocsProjectsRoute
  '/_authenticated/docs/rate-limiting': typeof AuthenticatedDocsRateLimitingRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_authenticated/$organizationId/': typeof AuthenticatedOrganizationIdIndexRoute
  '/_authenticated/docs/': typeof AuthenticatedDocsIndexRoute
  '/_authenticated/$organizationId/projects/$projectId': typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/_authenticated/$organizationId/settings/api-keys': typeof AuthenticatedOrganizationIdSettingsApiKeysRouteRouteWithChildren
  '/_authenticated/$organizationId/settings/general': typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren
  '/_authenticated/$organizationId/settings/members': typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren
  '/_authenticated/account/settings/authentication': typeof AuthenticatedAccountSettingsAuthenticationRouteRoute
  '/_authenticated/account/settings/general': typeof AuthenticatedAccountSettingsGeneralRouteRouteWithChildren
  '/api/v1/$organizationId/projects': typeof ApiV1OrganizationIdProjectsRouteRouteWithChildren
  '/_authenticated/$organizationId/projects/new': typeof AuthenticatedOrganizationIdProjectsNewRoute
  '/_authenticated/docs/api/auth': typeof AuthenticatedDocsApiAuthRoute
  '/_authenticated/docs/api/feedback': typeof AuthenticatedDocsApiFeedbackRoute
  '/_authenticated/docs/api/organizations': typeof AuthenticatedDocsApiOrganizationsRoute
  '/_authenticated/docs/api/overview': typeof AuthenticatedDocsApiOverviewRoute
  '/_authenticated/docs/api/projects': typeof AuthenticatedDocsApiProjectsRoute
  '/_authenticated/$organizationId/integrations/': typeof AuthenticatedOrganizationIdIntegrationsIndexRoute
  '/_authenticated/$organizationId/projects/$projectId/settings': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren
  '/api/v1/$organizationId/projects/$projectId': typeof ApiV1OrganizationIdProjectsProjectIdRouteRouteWithChildren
  '/_authenticated/$organizationId/projects/$projectId/feedback': typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute
  '/_authenticated/$organizationId/settings/api-keys/new': typeof AuthenticatedOrganizationIdSettingsApiKeysNewRoute
  '/_authenticated/$organizationId/settings/general/delete': typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRoute
  '/_authenticated/$organizationId/settings/members/invite': typeof AuthenticatedOrganizationIdSettingsMembersInviteRoute
  '/_authenticated/account/settings/general/delete': typeof AuthenticatedAccountSettingsGeneralDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteWithChildren
  '/_authenticated/$organizationId/projects/$projectId/settings/delete': typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute
  '/_authenticated/$organizationId/settings/api-keys/$apiKeyId/delete': typeof AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRoute
  '/_authenticated/$organizationId/settings/members/$memberId/delete': typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute
  '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId': typeof ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/$organizationId'
    | '/docs'
    | '/home'
    | '/new-organization'
    | '/settings'
    | '/invite/$token'
    | '/'
    | '/$organizationId/integrations'
    | '/$organizationId/settings'
    | '/account/settings'
    | '/api/v1/$organizationId'
    | '/docs/auth'
    | '/docs/feedback'
    | '/docs/notifications'
    | '/docs/organizations'
    | '/docs/projects'
    | '/docs/rate-limiting'
    | '/api/auth/$'
    | '/$organizationId/'
    | '/docs/'
    | '/$organizationId/projects/$projectId'
    | '/$organizationId/settings/api-keys'
    | '/$organizationId/settings/general'
    | '/$organizationId/settings/members'
    | '/account/settings/authentication'
    | '/account/settings/general'
    | '/api/v1/$organizationId/projects'
    | '/$organizationId/projects/new'
    | '/docs/api/auth'
    | '/docs/api/feedback'
    | '/docs/api/organizations'
    | '/docs/api/overview'
    | '/docs/api/projects'
    | '/$organizationId/integrations/'
    | '/$organizationId/projects/$projectId/settings'
    | '/api/v1/$organizationId/projects/$projectId'
    | '/$organizationId/projects/$projectId/feedback'
    | '/$organizationId/settings/api-keys/new'
    | '/$organizationId/settings/general/delete'
    | '/$organizationId/settings/members/invite'
    | '/account/settings/general/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback'
    | '/$organizationId/projects/$projectId/settings/delete'
    | '/$organizationId/settings/api-keys/$apiKeyId/delete'
    | '/$organizationId/settings/members/$memberId/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/home'
    | '/new-organization'
    | '/settings'
    | '/invite/$token'
    | '/'
    | '/$organizationId/settings'
    | '/account/settings'
    | '/api/v1/$organizationId'
    | '/docs/auth'
    | '/docs/feedback'
    | '/docs/notifications'
    | '/docs/organizations'
    | '/docs/projects'
    | '/docs/rate-limiting'
    | '/api/auth/$'
    | '/$organizationId'
    | '/docs'
    | '/$organizationId/projects/$projectId'
    | '/$organizationId/settings/api-keys'
    | '/$organizationId/settings/general'
    | '/$organizationId/settings/members'
    | '/account/settings/authentication'
    | '/account/settings/general'
    | '/api/v1/$organizationId/projects'
    | '/$organizationId/projects/new'
    | '/docs/api/auth'
    | '/docs/api/feedback'
    | '/docs/api/organizations'
    | '/docs/api/overview'
    | '/docs/api/projects'
    | '/$organizationId/integrations'
    | '/$organizationId/projects/$projectId/settings'
    | '/api/v1/$organizationId/projects/$projectId'
    | '/$organizationId/projects/$projectId/feedback'
    | '/$organizationId/settings/api-keys/new'
    | '/$organizationId/settings/general/delete'
    | '/$organizationId/settings/members/invite'
    | '/account/settings/general/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback'
    | '/$organizationId/projects/$projectId/settings/delete'
    | '/$organizationId/settings/api-keys/$apiKeyId/delete'
    | '/$organizationId/settings/members/$memberId/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/$organizationId'
    | '/_authenticated/docs'
    | '/_authenticated/home'
    | '/_authenticated/new-organization'
    | '/_authenticated/settings'
    | '/invite/$token'
    | '/_authenticated/'
    | '/_authenticated/$organizationId/integrations'
    | '/_authenticated/$organizationId/settings'
    | '/_authenticated/account/settings'
    | '/api/v1/$organizationId'
    | '/_authenticated/docs/auth'
    | '/_authenticated/docs/feedback'
    | '/_authenticated/docs/notifications'
    | '/_authenticated/docs/organizations'
    | '/_authenticated/docs/projects'
    | '/_authenticated/docs/rate-limiting'
    | '/api/auth/$'
    | '/_authenticated/$organizationId/'
    | '/_authenticated/docs/'
    | '/_authenticated/$organizationId/projects/$projectId'
    | '/_authenticated/$organizationId/settings/api-keys'
    | '/_authenticated/$organizationId/settings/general'
    | '/_authenticated/$organizationId/settings/members'
    | '/_authenticated/account/settings/authentication'
    | '/_authenticated/account/settings/general'
    | '/api/v1/$organizationId/projects'
    | '/_authenticated/$organizationId/projects/new'
    | '/_authenticated/docs/api/auth'
    | '/_authenticated/docs/api/feedback'
    | '/_authenticated/docs/api/organizations'
    | '/_authenticated/docs/api/overview'
    | '/_authenticated/docs/api/projects'
    | '/_authenticated/$organizationId/integrations/'
    | '/_authenticated/$organizationId/projects/$projectId/settings'
    | '/api/v1/$organizationId/projects/$projectId'
    | '/_authenticated/$organizationId/projects/$projectId/feedback'
    | '/_authenticated/$organizationId/settings/api-keys/new'
    | '/_authenticated/$organizationId/settings/general/delete'
    | '/_authenticated/$organizationId/settings/members/invite'
    | '/_authenticated/account/settings/general/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback'
    | '/_authenticated/$organizationId/projects/$projectId/settings/delete'
    | '/_authenticated/$organizationId/settings/api-keys/$apiKeyId/delete'
    | '/_authenticated/$organizationId/settings/members/$memberId/delete'
    | '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiV1OrganizationIdRouteRoute: typeof ApiV1OrganizationIdRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new-organization': {
      id: '/_authenticated/new-organization'
      path: '/new-organization'
      fullPath: '/new-organization'
      preLoaderRoute: typeof AuthenticatedNewOrganizationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs': {
      id: '/_authenticated/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof AuthenticatedDocsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$organizationId': {
      id: '/_authenticated/$organizationId'
      path: '/$organizationId'
      fullPath: '/$organizationId'
      preLoaderRoute: typeof AuthenticatedOrganizationIdRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/docs/': {
      id: '/_authenticated/docs/'
      path: '/'
      fullPath: '/docs/'
      preLoaderRoute: typeof AuthenticatedDocsIndexRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/$organizationId/': {
      id: '/_authenticated/$organizationId/'
      path: '/'
      fullPath: '/$organizationId/'
      preLoaderRoute: typeof AuthenticatedOrganizationIdIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/docs/rate-limiting': {
      id: '/_authenticated/docs/rate-limiting'
      path: '/rate-limiting'
      fullPath: '/docs/rate-limiting'
      preLoaderRoute: typeof AuthenticatedDocsRateLimitingRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/projects': {
      id: '/_authenticated/docs/projects'
      path: '/projects'
      fullPath: '/docs/projects'
      preLoaderRoute: typeof AuthenticatedDocsProjectsRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/organizations': {
      id: '/_authenticated/docs/organizations'
      path: '/organizations'
      fullPath: '/docs/organizations'
      preLoaderRoute: typeof AuthenticatedDocsOrganizationsRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/notifications': {
      id: '/_authenticated/docs/notifications'
      path: '/notifications'
      fullPath: '/docs/notifications'
      preLoaderRoute: typeof AuthenticatedDocsNotificationsRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/feedback': {
      id: '/_authenticated/docs/feedback'
      path: '/feedback'
      fullPath: '/docs/feedback'
      preLoaderRoute: typeof AuthenticatedDocsFeedbackRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/auth': {
      id: '/_authenticated/docs/auth'
      path: '/auth'
      fullPath: '/docs/auth'
      preLoaderRoute: typeof AuthenticatedDocsAuthRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/api/v1/$organizationId': {
      id: '/api/v1/$organizationId'
      path: '/api/v1/$organizationId'
      fullPath: '/api/v1/$organizationId'
      preLoaderRoute: typeof ApiV1OrganizationIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/account/settings': {
      id: '/_authenticated/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AuthenticatedAccountSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/$organizationId/settings': {
      id: '/_authenticated/$organizationId/settings'
      path: '/settings'
      fullPath: '/$organizationId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/_authenticated/$organizationId/integrations': {
      id: '/_authenticated/$organizationId/integrations'
      path: '/integrations'
      fullPath: '/$organizationId/integrations'
      preLoaderRoute: typeof AuthenticatedOrganizationIdIntegrationsRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/_authenticated/$organizationId/integrations/': {
      id: '/_authenticated/$organizationId/integrations/'
      path: '/'
      fullPath: '/$organizationId/integrations/'
      preLoaderRoute: typeof AuthenticatedOrganizationIdIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdIntegrationsRouteRoute
    }
    '/_authenticated/docs/api/projects': {
      id: '/_authenticated/docs/api/projects'
      path: '/api/projects'
      fullPath: '/docs/api/projects'
      preLoaderRoute: typeof AuthenticatedDocsApiProjectsRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/api/overview': {
      id: '/_authenticated/docs/api/overview'
      path: '/api/overview'
      fullPath: '/docs/api/overview'
      preLoaderRoute: typeof AuthenticatedDocsApiOverviewRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/api/organizations': {
      id: '/_authenticated/docs/api/organizations'
      path: '/api/organizations'
      fullPath: '/docs/api/organizations'
      preLoaderRoute: typeof AuthenticatedDocsApiOrganizationsRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/api/feedback': {
      id: '/_authenticated/docs/api/feedback'
      path: '/api/feedback'
      fullPath: '/docs/api/feedback'
      preLoaderRoute: typeof AuthenticatedDocsApiFeedbackRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/docs/api/auth': {
      id: '/_authenticated/docs/api/auth'
      path: '/api/auth'
      fullPath: '/docs/api/auth'
      preLoaderRoute: typeof AuthenticatedDocsApiAuthRouteImport
      parentRoute: typeof AuthenticatedDocsRouteRoute
    }
    '/_authenticated/$organizationId/projects/new': {
      id: '/_authenticated/$organizationId/projects/new'
      path: '/projects/new'
      fullPath: '/$organizationId/projects/new'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsNewRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/api/v1/$organizationId/projects': {
      id: '/api/v1/$organizationId/projects'
      path: '/projects'
      fullPath: '/api/v1/$organizationId/projects'
      preLoaderRoute: typeof ApiV1OrganizationIdProjectsRouteRouteImport
      parentRoute: typeof ApiV1OrganizationIdRouteRoute
    }
    '/_authenticated/account/settings/general': {
      id: '/_authenticated/account/settings/general'
      path: '/general'
      fullPath: '/account/settings/general'
      preLoaderRoute: typeof AuthenticatedAccountSettingsGeneralRouteRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRouteRoute
    }
    '/_authenticated/account/settings/authentication': {
      id: '/_authenticated/account/settings/authentication'
      path: '/authentication'
      fullPath: '/account/settings/authentication'
      preLoaderRoute: typeof AuthenticatedAccountSettingsAuthenticationRouteRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsRouteRoute
    }
    '/_authenticated/$organizationId/settings/members': {
      id: '/_authenticated/$organizationId/settings/members'
      path: '/members'
      fullPath: '/$organizationId/settings/members'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsRouteRoute
    }
    '/_authenticated/$organizationId/settings/general': {
      id: '/_authenticated/$organizationId/settings/general'
      path: '/general'
      fullPath: '/$organizationId/settings/general'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsRouteRoute
    }
    '/_authenticated/$organizationId/settings/api-keys': {
      id: '/_authenticated/$organizationId/settings/api-keys'
      path: '/api-keys'
      fullPath: '/$organizationId/settings/api-keys'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsApiKeysRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsRouteRoute
    }
    '/_authenticated/$organizationId/projects/$projectId': {
      id: '/_authenticated/$organizationId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/$organizationId/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdRouteRoute
    }
    '/_authenticated/account/settings/general/delete': {
      id: '/_authenticated/account/settings/general/delete'
      path: '/delete'
      fullPath: '/account/settings/general/delete'
      preLoaderRoute: typeof AuthenticatedAccountSettingsGeneralDeleteRouteImport
      parentRoute: typeof AuthenticatedAccountSettingsGeneralRouteRoute
    }
    '/_authenticated/$organizationId/settings/members/invite': {
      id: '/_authenticated/$organizationId/settings/members/invite'
      path: '/invite'
      fullPath: '/$organizationId/settings/members/invite'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsMembersInviteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsMembersRouteRoute
    }
    '/_authenticated/$organizationId/settings/general/delete': {
      id: '/_authenticated/$organizationId/settings/general/delete'
      path: '/delete'
      fullPath: '/$organizationId/settings/general/delete'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsGeneralRouteRoute
    }
    '/_authenticated/$organizationId/settings/api-keys/new': {
      id: '/_authenticated/$organizationId/settings/api-keys/new'
      path: '/new'
      fullPath: '/$organizationId/settings/api-keys/new'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsApiKeysNewRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsApiKeysRouteRoute
    }
    '/_authenticated/$organizationId/projects/$projectId/feedback': {
      id: '/_authenticated/$organizationId/projects/$projectId/feedback'
      path: '/feedback'
      fullPath: '/$organizationId/projects/$projectId/feedback'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRoute
    }
    '/api/v1/$organizationId/projects/$projectId': {
      id: '/api/v1/$organizationId/projects/$projectId'
      path: '/$projectId'
      fullPath: '/api/v1/$organizationId/projects/$projectId'
      preLoaderRoute: typeof ApiV1OrganizationIdProjectsProjectIdRouteRouteImport
      parentRoute: typeof ApiV1OrganizationIdProjectsRouteRoute
    }
    '/_authenticated/$organizationId/projects/$projectId/settings': {
      id: '/_authenticated/$organizationId/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/$organizationId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRoute
    }
    '/_authenticated/$organizationId/settings/members/$memberId/delete': {
      id: '/_authenticated/$organizationId/settings/members/$memberId/delete'
      path: '/$memberId/delete'
      fullPath: '/$organizationId/settings/members/$memberId/delete'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsMembersRouteRoute
    }
    '/_authenticated/$organizationId/settings/api-keys/$apiKeyId/delete': {
      id: '/_authenticated/$organizationId/settings/api-keys/$apiKeyId/delete'
      path: '/$apiKeyId/delete'
      fullPath: '/$organizationId/settings/api-keys/$apiKeyId/delete'
      preLoaderRoute: typeof AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdSettingsApiKeysRouteRoute
    }
    '/_authenticated/$organizationId/projects/$projectId/settings/delete': {
      id: '/_authenticated/$organizationId/projects/$projectId/settings/delete'
      path: '/delete'
      fullPath: '/$organizationId/projects/$projectId/settings/delete'
      preLoaderRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRouteImport
      parentRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute
    }
    '/api/v1/$organizationId/projects/$projectId/feedback': {
      id: '/api/v1/$organizationId/projects/$projectId/feedback'
      path: '/feedback'
      fullPath: '/api/v1/$organizationId/projects/$projectId/feedback'
      preLoaderRoute: typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteImport
      parentRoute: typeof ApiV1OrganizationIdProjectsProjectIdRouteRoute
    }
    '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId': {
      id: '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId'
      path: '/$feedbackId'
      fullPath: '/api/v1/$organizationId/projects/$projectId/feedback/$feedbackId'
      preLoaderRoute: typeof ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRouteImport
      parentRoute: typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRoute
    }
  }
}

interface AuthenticatedOrganizationIdIntegrationsRouteRouteChildren {
  AuthenticatedOrganizationIdIntegrationsIndexRoute: typeof AuthenticatedOrganizationIdIntegrationsIndexRoute
}

const AuthenticatedOrganizationIdIntegrationsRouteRouteChildren: AuthenticatedOrganizationIdIntegrationsRouteRouteChildren =
  {
    AuthenticatedOrganizationIdIntegrationsIndexRoute:
      AuthenticatedOrganizationIdIntegrationsIndexRoute,
  }

const AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren =
  AuthenticatedOrganizationIdIntegrationsRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdIntegrationsRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdSettingsApiKeysRouteRouteChildren {
  AuthenticatedOrganizationIdSettingsApiKeysNewRoute: typeof AuthenticatedOrganizationIdSettingsApiKeysNewRoute
  AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRoute: typeof AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRoute
}

const AuthenticatedOrganizationIdSettingsApiKeysRouteRouteChildren: AuthenticatedOrganizationIdSettingsApiKeysRouteRouteChildren =
  {
    AuthenticatedOrganizationIdSettingsApiKeysNewRoute:
      AuthenticatedOrganizationIdSettingsApiKeysNewRoute,
    AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRoute:
      AuthenticatedOrganizationIdSettingsApiKeysApiKeyIdDeleteRoute,
  }

const AuthenticatedOrganizationIdSettingsApiKeysRouteRouteWithChildren =
  AuthenticatedOrganizationIdSettingsApiKeysRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdSettingsApiKeysRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdSettingsGeneralRouteRouteChildren {
  AuthenticatedOrganizationIdSettingsGeneralDeleteRoute: typeof AuthenticatedOrganizationIdSettingsGeneralDeleteRoute
}

const AuthenticatedOrganizationIdSettingsGeneralRouteRouteChildren: AuthenticatedOrganizationIdSettingsGeneralRouteRouteChildren =
  {
    AuthenticatedOrganizationIdSettingsGeneralDeleteRoute:
      AuthenticatedOrganizationIdSettingsGeneralDeleteRoute,
  }

const AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren =
  AuthenticatedOrganizationIdSettingsGeneralRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdSettingsGeneralRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdSettingsMembersRouteRouteChildren {
  AuthenticatedOrganizationIdSettingsMembersInviteRoute: typeof AuthenticatedOrganizationIdSettingsMembersInviteRoute
  AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute: typeof AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute
}

const AuthenticatedOrganizationIdSettingsMembersRouteRouteChildren: AuthenticatedOrganizationIdSettingsMembersRouteRouteChildren =
  {
    AuthenticatedOrganizationIdSettingsMembersInviteRoute:
      AuthenticatedOrganizationIdSettingsMembersInviteRoute,
    AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute:
      AuthenticatedOrganizationIdSettingsMembersMemberIdDeleteRoute,
  }

const AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren =
  AuthenticatedOrganizationIdSettingsMembersRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdSettingsMembersRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdSettingsRouteRouteChildren {
  AuthenticatedOrganizationIdSettingsApiKeysRouteRoute: typeof AuthenticatedOrganizationIdSettingsApiKeysRouteRouteWithChildren
  AuthenticatedOrganizationIdSettingsGeneralRouteRoute: typeof AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren
  AuthenticatedOrganizationIdSettingsMembersRouteRoute: typeof AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren
}

const AuthenticatedOrganizationIdSettingsRouteRouteChildren: AuthenticatedOrganizationIdSettingsRouteRouteChildren =
  {
    AuthenticatedOrganizationIdSettingsApiKeysRouteRoute:
      AuthenticatedOrganizationIdSettingsApiKeysRouteRouteWithChildren,
    AuthenticatedOrganizationIdSettingsGeneralRouteRoute:
      AuthenticatedOrganizationIdSettingsGeneralRouteRouteWithChildren,
    AuthenticatedOrganizationIdSettingsMembersRouteRoute:
      AuthenticatedOrganizationIdSettingsMembersRouteRouteWithChildren,
  }

const AuthenticatedOrganizationIdSettingsRouteRouteWithChildren =
  AuthenticatedOrganizationIdSettingsRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdSettingsRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteChildren {
  AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute
}

const AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteChildren: AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteChildren =
  {
    AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute:
      AuthenticatedOrganizationIdProjectsProjectIdSettingsDeleteRoute,
  }

const AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren =
  AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdProjectsProjectIdRouteRouteChildren {
  AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren
  AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute
}

const AuthenticatedOrganizationIdProjectsProjectIdRouteRouteChildren: AuthenticatedOrganizationIdProjectsProjectIdRouteRouteChildren =
  {
    AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRoute:
      AuthenticatedOrganizationIdProjectsProjectIdSettingsRouteRouteWithChildren,
    AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute:
      AuthenticatedOrganizationIdProjectsProjectIdFeedbackRoute,
  }

const AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren =
  AuthenticatedOrganizationIdProjectsProjectIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdProjectsProjectIdRouteRouteChildren,
  )

interface AuthenticatedOrganizationIdRouteRouteChildren {
  AuthenticatedOrganizationIdIntegrationsRouteRoute: typeof AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren
  AuthenticatedOrganizationIdSettingsRouteRoute: typeof AuthenticatedOrganizationIdSettingsRouteRouteWithChildren
  AuthenticatedOrganizationIdIndexRoute: typeof AuthenticatedOrganizationIdIndexRoute
  AuthenticatedOrganizationIdProjectsProjectIdRouteRoute: typeof AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren
  AuthenticatedOrganizationIdProjectsNewRoute: typeof AuthenticatedOrganizationIdProjectsNewRoute
}

const AuthenticatedOrganizationIdRouteRouteChildren: AuthenticatedOrganizationIdRouteRouteChildren =
  {
    AuthenticatedOrganizationIdIntegrationsRouteRoute:
      AuthenticatedOrganizationIdIntegrationsRouteRouteWithChildren,
    AuthenticatedOrganizationIdSettingsRouteRoute:
      AuthenticatedOrganizationIdSettingsRouteRouteWithChildren,
    AuthenticatedOrganizationIdIndexRoute:
      AuthenticatedOrganizationIdIndexRoute,
    AuthenticatedOrganizationIdProjectsProjectIdRouteRoute:
      AuthenticatedOrganizationIdProjectsProjectIdRouteRouteWithChildren,
    AuthenticatedOrganizationIdProjectsNewRoute:
      AuthenticatedOrganizationIdProjectsNewRoute,
  }

const AuthenticatedOrganizationIdRouteRouteWithChildren =
  AuthenticatedOrganizationIdRouteRoute._addFileChildren(
    AuthenticatedOrganizationIdRouteRouteChildren,
  )

interface AuthenticatedDocsRouteRouteChildren {
  AuthenticatedDocsAuthRoute: typeof AuthenticatedDocsAuthRoute
  AuthenticatedDocsFeedbackRoute: typeof AuthenticatedDocsFeedbackRoute
  AuthenticatedDocsNotificationsRoute: typeof AuthenticatedDocsNotificationsRoute
  AuthenticatedDocsOrganizationsRoute: typeof AuthenticatedDocsOrganizationsRoute
  AuthenticatedDocsProjectsRoute: typeof AuthenticatedDocsProjectsRoute
  AuthenticatedDocsRateLimitingRoute: typeof AuthenticatedDocsRateLimitingRoute
  AuthenticatedDocsIndexRoute: typeof AuthenticatedDocsIndexRoute
  AuthenticatedDocsApiAuthRoute: typeof AuthenticatedDocsApiAuthRoute
  AuthenticatedDocsApiFeedbackRoute: typeof AuthenticatedDocsApiFeedbackRoute
  AuthenticatedDocsApiOrganizationsRoute: typeof AuthenticatedDocsApiOrganizationsRoute
  AuthenticatedDocsApiOverviewRoute: typeof AuthenticatedDocsApiOverviewRoute
  AuthenticatedDocsApiProjectsRoute: typeof AuthenticatedDocsApiProjectsRoute
}

const AuthenticatedDocsRouteRouteChildren: AuthenticatedDocsRouteRouteChildren =
  {
    AuthenticatedDocsAuthRoute: AuthenticatedDocsAuthRoute,
    AuthenticatedDocsFeedbackRoute: AuthenticatedDocsFeedbackRoute,
    AuthenticatedDocsNotificationsRoute: AuthenticatedDocsNotificationsRoute,
    AuthenticatedDocsOrganizationsRoute: AuthenticatedDocsOrganizationsRoute,
    AuthenticatedDocsProjectsRoute: AuthenticatedDocsProjectsRoute,
    AuthenticatedDocsRateLimitingRoute: AuthenticatedDocsRateLimitingRoute,
    AuthenticatedDocsIndexRoute: AuthenticatedDocsIndexRoute,
    AuthenticatedDocsApiAuthRoute: AuthenticatedDocsApiAuthRoute,
    AuthenticatedDocsApiFeedbackRoute: AuthenticatedDocsApiFeedbackRoute,
    AuthenticatedDocsApiOrganizationsRoute:
      AuthenticatedDocsApiOrganizationsRoute,
    AuthenticatedDocsApiOverviewRoute: AuthenticatedDocsApiOverviewRoute,
    AuthenticatedDocsApiProjectsRoute: AuthenticatedDocsApiProjectsRoute,
  }

const AuthenticatedDocsRouteRouteWithChildren =
  AuthenticatedDocsRouteRoute._addFileChildren(
    AuthenticatedDocsRouteRouteChildren,
  )

interface AuthenticatedAccountSettingsGeneralRouteRouteChildren {
  AuthenticatedAccountSettingsGeneralDeleteRoute: typeof AuthenticatedAccountSettingsGeneralDeleteRoute
}

const AuthenticatedAccountSettingsGeneralRouteRouteChildren: AuthenticatedAccountSettingsGeneralRouteRouteChildren =
  {
    AuthenticatedAccountSettingsGeneralDeleteRoute:
      AuthenticatedAccountSettingsGeneralDeleteRoute,
  }

const AuthenticatedAccountSettingsGeneralRouteRouteWithChildren =
  AuthenticatedAccountSettingsGeneralRouteRoute._addFileChildren(
    AuthenticatedAccountSettingsGeneralRouteRouteChildren,
  )

interface AuthenticatedAccountSettingsRouteRouteChildren {
  AuthenticatedAccountSettingsAuthenticationRouteRoute: typeof AuthenticatedAccountSettingsAuthenticationRouteRoute
  AuthenticatedAccountSettingsGeneralRouteRoute: typeof AuthenticatedAccountSettingsGeneralRouteRouteWithChildren
}

const AuthenticatedAccountSettingsRouteRouteChildren: AuthenticatedAccountSettingsRouteRouteChildren =
  {
    AuthenticatedAccountSettingsAuthenticationRouteRoute:
      AuthenticatedAccountSettingsAuthenticationRouteRoute,
    AuthenticatedAccountSettingsGeneralRouteRoute:
      AuthenticatedAccountSettingsGeneralRouteRouteWithChildren,
  }

const AuthenticatedAccountSettingsRouteRouteWithChildren =
  AuthenticatedAccountSettingsRouteRoute._addFileChildren(
    AuthenticatedAccountSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOrganizationIdRouteRoute: typeof AuthenticatedOrganizationIdRouteRouteWithChildren
  AuthenticatedDocsRouteRoute: typeof AuthenticatedDocsRouteRouteWithChildren
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedNewOrganizationRoute: typeof AuthenticatedNewOrganizationRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAccountSettingsRouteRoute: typeof AuthenticatedAccountSettingsRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOrganizationIdRouteRoute:
    AuthenticatedOrganizationIdRouteRouteWithChildren,
  AuthenticatedDocsRouteRoute: AuthenticatedDocsRouteRouteWithChildren,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedNewOrganizationRoute: AuthenticatedNewOrganizationRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAccountSettingsRouteRoute:
    AuthenticatedAccountSettingsRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteChildren {
  ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRoute: typeof ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRoute
}

const ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteChildren: ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteChildren =
  {
    ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRoute:
      ApiV1OrganizationIdProjectsProjectIdFeedbackFeedbackIdRoute,
  }

const ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteWithChildren =
  ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRoute._addFileChildren(
    ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteChildren,
  )

interface ApiV1OrganizationIdProjectsProjectIdRouteRouteChildren {
  ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRoute: typeof ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteWithChildren
}

const ApiV1OrganizationIdProjectsProjectIdRouteRouteChildren: ApiV1OrganizationIdProjectsProjectIdRouteRouteChildren =
  {
    ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRoute:
      ApiV1OrganizationIdProjectsProjectIdFeedbackRouteRouteWithChildren,
  }

const ApiV1OrganizationIdProjectsProjectIdRouteRouteWithChildren =
  ApiV1OrganizationIdProjectsProjectIdRouteRoute._addFileChildren(
    ApiV1OrganizationIdProjectsProjectIdRouteRouteChildren,
  )

interface ApiV1OrganizationIdProjectsRouteRouteChildren {
  ApiV1OrganizationIdProjectsProjectIdRouteRoute: typeof ApiV1OrganizationIdProjectsProjectIdRouteRouteWithChildren
}

const ApiV1OrganizationIdProjectsRouteRouteChildren: ApiV1OrganizationIdProjectsRouteRouteChildren =
  {
    ApiV1OrganizationIdProjectsProjectIdRouteRoute:
      ApiV1OrganizationIdProjectsProjectIdRouteRouteWithChildren,
  }

const ApiV1OrganizationIdProjectsRouteRouteWithChildren =
  ApiV1OrganizationIdProjectsRouteRoute._addFileChildren(
    ApiV1OrganizationIdProjectsRouteRouteChildren,
  )

interface ApiV1OrganizationIdRouteRouteChildren {
  ApiV1OrganizationIdProjectsRouteRoute: typeof ApiV1OrganizationIdProjectsRouteRouteWithChildren
}

const ApiV1OrganizationIdRouteRouteChildren: ApiV1OrganizationIdRouteRouteChildren =
  {
    ApiV1OrganizationIdProjectsRouteRoute:
      ApiV1OrganizationIdProjectsRouteRouteWithChildren,
  }

const ApiV1OrganizationIdRouteRouteWithChildren =
  ApiV1OrganizationIdRouteRoute._addFileChildren(
    ApiV1OrganizationIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiV1OrganizationIdRouteRoute: ApiV1OrganizationIdRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
